version: "3.8"

services:
  db_product:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    volumes:
      - ./product-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  db_cart:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cart_db
    volumes:
      - ./cart-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  db_order:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    volumes:
      - ./order-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - db_product

  cart-service:
    build: ./cart-service
    ports:
      - "3002:3002"
    depends_on:
      - db_cart

  order-service:
    build: ./order-service
    ports:
      - "3003:3003"
    depends_on:
      - db_order

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - cart-service
      - order-service
